INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, '127 Hours (2010).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, '2001 A Space Odyssey (1968).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, '30 Days of Night (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Ace Ventura Pet Detective (1994).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Across the Universe (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Adaptation. (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'A.I. Artificial Intelligence (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Akira (1988).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Alien (1979).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Aliens (1986).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Altered States (1980).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Amazon Women on the Moon (1987).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'American Gangster (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'American Psycho (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Anchorman The Legend of Ron Burgundy (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Anger Management (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'A Night at the Roxbury (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Apocalypse Now (1979).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Apocalypse Now_D1.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Apocalypse Now_D2.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Aqua Teen Hunger Force Colon Movie Film for Theaters (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Army of Darkness (1992).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'ARMY_OF_DARKNESS.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'A Scanner Darkly (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'As Good as It Gets (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Austin Powers in Goldmember (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Austin Powers International Man of Mystery (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Austin Powers The Spy Who Shagged Me (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Avatar (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'A Very Harold and Kumar Christmas (2011).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'AVP Alien vs. Predator (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Baby''s Day Out (1994).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bad Santa (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bad Taste (1987).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Beavis and Butt-Head Do America (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bedazzled (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Beerfest (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Big Fish (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bill and Ted''s Bogus Journey (1991).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bill and Ted''s Excellent Adventure (1989).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Billy Madison (1995).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Black Brigade (1970).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Blackmail (1929).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Black Sheep (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Blade Runner (1982).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Blazing Saddles (1974).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Blood Diamond (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Blood Into Wine (2010).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Blue Velvet (1986).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Boogie Nights (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Brazil (1985).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Breathless (1960).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bring It On (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bruce Almighty (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bruno (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Bulworth (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Burn After Reading (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'BUTTERFLY_EFFECT directors cut.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Carriers (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Casablanca (1942).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Children of Men (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'CHRISTMAS_WITH_GUMBY_05_81554.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'C.H.U.D. (1984).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Citizen Kane (1941).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'City of Angels (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'CKY2K (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'CKY 3 (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'CKY 4 The Latest and Greatest (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Clerks (1994).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Closer (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Coraline (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Cowboy Bebop The Movie (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Crash (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dances with Wolves (1990).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dark City (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dark Days (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Date Night (2010).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dawn of the Dead (1978).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dawn of the Dead (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dazed and Confused (1993).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dead Alive (1992).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Deep Impact (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Deliverance (1972).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dementia 13 (1963).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dennis the Menace (1993).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Destination Tokyo (1943).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dog Day Afternoon (1975).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Don''t Be a Menace to South Central While Drinking Your Juice in the Hood (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'DON_T_LET_ME_DOWN_DVD.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Doomsday (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Drag Me to Hell (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb (1964).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Dune (1984).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'DUNE.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Empire of the Sun (1987).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Enemy at the Gates (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Enemy Mine (1985).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Erin Brockovich (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'EuroTrip (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Event Horizon (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Evil Dead (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Evil Dead II (1987).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Ewoks The Battle for Endor (1985).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'eXistenZ (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Fahrenheit 451 (1966).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Fargo (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Fear (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Fear and Loathing in Las Vegas (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Fellini Satyricon (1969).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Final Days of Planet Earth (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Fortress (1993).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Freddy Got Fingered (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Friday (1995).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Friday After Next (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'From Hell (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'FrostNixon (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Galaxy Quest (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Gattaca (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Ghostbusters II (1989).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Gonzo The Life and Work of Dr. Hunter S. Thompson (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Goodfellas (1990).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Grandma''s Boy (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Gran Torino (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Happy Gilmore (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Harold and Kumar Go to White Castle (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'HAROLD_AND_KUMAR_WHITE_CASTLE.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Hitch (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Hollow Man (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Identity Thief (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Idiocracy (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'IDIOCRACY.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Inception (2010).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Independence Day (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Invasion of the Body Snatchers (1956).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'I Was Nineteen (1968).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Jackass The Movie (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Jacob''s Ladder (1990).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Jay And Silent Bob Strike Back (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Jim Gaffigan King Baby (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Jin-Roh The Wolf Brigade (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Jumanji (1995).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Kill Bill Vol. 1 (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Kill Bill Vol. 2 (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Landspeed presents CKY (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Laserhawk (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Last Action Hero (1993).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Layer Cake (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Little Nicky (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Logan''s Run (1976).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Mallrats (1995).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'MALLRATS_DIRECTORS_CUT.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Mean Guns (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Meet the Fockers (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Me, Myself and Irene (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Milk (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Mission Impossible (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Mitch Hedberg Mitch All Together (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Mona Lisa Smile (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Monster''s Ball (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Much Ado About Nothing (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Mud (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'names');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Next Friday (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Night of the Living Dead (1968).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'O Brother, Where Art Thou (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Old School (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'One Flew Over the Cuckoo''s Nest (1975).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Ong Bak (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Only God Forgives (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Phantoms (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Phenomenon (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Pi (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Pink Flamingos (1972).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Platoon (1986).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Predator (1987).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Predator 2 (1990).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Raging Bull (1980).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Raising Arizona (1987).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Rat Race (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Ravenous (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Red Dragon (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Rent (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Reservoir Dogs (1992).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Resident Evil (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Ring 2 (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'RocketMan (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Romancing the Stone (1984).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Roman Holiday (1953).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Romeo + Juliet (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Rubber (2010).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Rush Hour 2 (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Scarface (1983).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Scary Movie (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Schizopolis (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'SECRETARY.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Shooter (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Signs (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Skin Deep (1989).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Sling Blade (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'SLINGblade.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Slums of Beverly Hills (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Sneakers (1992).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'SNL_Chris Farley.iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'SNL_Will Ferrell.iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Solaris (1972).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Sorcerer (1977).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Sphere (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Spider-Man (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Stargate (1994).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek First Contact (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek Generations (1994).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek III The Search for Spock (1984).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek II The Wrath of Khan (1982).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek Insurrection (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek IV The Voyage Home (1986).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek Nemesis (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek The Motion Picture (1979).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek VI The Undiscovered Country (1991).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Trek V The Final Frontier (1989).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Wars Episode II - Attack of the Clones (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Wars Episode III - Revenge of the Sith (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Wars Episode I - The Phantom Menace (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Wars Episode IV - A New Hope (1977).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Wars Episode VI - Return of the Jedi (1983).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Wars Episode V - The Empire Strikes Back (1980).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Star Wars Ewok Adventures - Caravan of Courage (1984).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Stay (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'STORM_OF_THE_CENTURY_SIDE_ONE.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'STORM_OF_THE_CENTURY_SIDE_TWO.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Stranger Than Fiction (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Sucker Punch (2011).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Super Mario Bros. (1993).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Supernova (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Superstar (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Taxi Driver (1976).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Tenacious D in The Pick of Destiny (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Terminator 3 Rise of the Machines (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Tetsuo, the Iron Man (1989).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Thank You for Smoking (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Amityville Horror (1979).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Animatrix (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Aristocrats (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Assassination of Jesse James by the Coward Robert Ford (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Bad Lieutenant Port of Call - New Orleans (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Black Hole (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Bling Ring (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Book of Eli (2010).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Butterfly Effect (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Cable Guy (1996).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'the cable guy.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Cider House Rules (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Corruptor (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Crow (1994).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Curious Case of Benjamin Button (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Evil Dead (1981).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Faculty (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Fifth Element (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Final Cut (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Fly (1958).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Fountain (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Fugitive (1993).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Gene Generation (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Gift (2000).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Girlfriend Experience (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Good, the Bad and the Ugly (1966).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THE_GREAT_GATSBY.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Guns of Navarone (1961).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Hobbit An Unexpected Journey (2012).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Hot Chick (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Human Stain (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The International (2009).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Lady Vanishes (1938).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Last Drop (2006).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Last Sentinel (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Lord of the Rings The Fellowship of the Ring (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Lord of the Rings The Return of the King (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Lord of the Rings The Two Towers (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Man Who Fell To Earth (1976).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THE_MASK.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Matrix (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Matrix Reloaded (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Matrix Revolutions (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Mist (2007).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Ninth Gate (1999).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THE_NOTEBOOK.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Outlaw Josey Wales (1976).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Place Beyond the Pines (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THE_PRINCESS_BRIDE_DISC1.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Protector (2005).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Punisher (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Ring (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Running Man (1987).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Santa Clause (1994).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Santa Clause 2 (2002).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THE_SHAWSHANK_REDEMPTION.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Texas Chainsaw Massacre (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Usual Suspects (1995).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Village (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Will.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'The Wrestler (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THIRTEEN_WS.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'This Is 40 (2012).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THIS_IS_THE_END.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'THX 1138 (1971).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Timeline (2003).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Total Recall (1990).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Tremors (1990).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Tremors 3 Back to Perfection (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Tremors 4 The Legend Begins (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'TRISTAN_ISOLDE_4X3.ISO');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Twelve Monkeys (1995).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Vampire Hunter D (1985).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Vanilla Sky (2001).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Very Bad Things (1998).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Wag the Dog (1997).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Walking Tall (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Waltz with Bashir (2008).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Warm Bodies (2013).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Without a Paddle (2004).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Wizards (1977).iso');
INSERT INTO Movies (collectionId, isRenamed, filename) VALUES (1, 0, 'Zombieland (2009).iso');
